name: Solidity CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install -g yarn
    - run: yarn install
    - run: yarn lint
    - run: yarn test
