name: Solidity CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        MNEMONIC: "laptop demise champion palace grab vapor either number coast patient then priority"
        MAINNET_PRIVATE_KEY: "0xb1a4373f2a59b540f016383744ef194f7108f0bd11b34bfdaac69e28030a35e7"
        INFURA_API_KEY: "460ed70fa7394604a709b7dff23f1641"
        ALCHEMY_API_KEY: "_H3tl1xfDKddnitmisPE4_0trJiEEaG4"
        file_name: .env
        fail_on_empty: false
        
  test:

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ matrix.os }}-yarn-
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn test
